export enum CanvasActions {
  UPDATE_CANVAS = 'UPDATE_CANVAS',
  UNDO_CANVAS = 'UNDO_CANVAS',
  REDO_CANVAS = 'REDO_CANVAS',
  LOAD_CANVAS = 'LOAD_CANVAS',
  INIT_CANVAS = 'INIT_CANVAS',
  SET_FLOOR_IMAGE = 'SET_FLOOR_IMAGE',
}
