export enum RoomEvent {
  ON_MEMBER_STATUS_CHANGED = 'ON_MEMBER_STATUS_CHANGED',
  ON_OBJECTS_BROADCASTED = 'ON_OBJECTS_BROADCASTED',
  ON_OBJECTS_SENT = 'ON_OBJECTS_SENT',
  ON_OBJECTS_AKED = 'ON_OBJECTS_AKED',
  ON_EXCEPTION = 'ON_EXCEPTION',
}
