export enum WebsocketStatus {
  UNKNOWN = 'UNKNOWN',
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  JOINED = 'JOINED',
  LEAVED = 'LEAVED',
  LISTENING = 'LISTENING',
  EJECTED = 'EJECTED',
  CLOSED = 'CLOSED',
}
