export enum DrawActions {
  CREATE = 'CREATE',
  LOAD = 'LOAD',
  SAVE = 'SAVE',
  DELETE = 'DELETE',
  UPDATE_STRAT = 'UPDATE_STRAT',
  SET_ACTIVE_LAYER = 'SET_ACTIVE_LAYER',
  TOOGLE_TACTICAL_MODE = 'TOOGLE_TACTICAL_MODE',
  SAVING = 'SAVING',
  UPDATE_LAYER = 'UPDATE_LAYER',
}
