export enum RoomChannel {
  LEAVE = 'LEAVE',
  EJECT = 'EJECT',
  BROADCAST_OBJECT_LIST = 'BROADCAST_OBJECTS_LIST',
  ASK_OBJECTS_FROM_LIST = 'ASK_OBJECTS_FROM_LIST',
  SEND_PLAIN_OBJECTS = 'SEND_PLAIN_OBJECTS',
  EVENTS = 'EVENTS',
  CLOSE_ROOM = 'CLOSE_ROOM',
  JOIN = 'JOIN',
  USER_ACTIONS = 'USER_ACTIONS',
}
